### ISSUE TITLE
关于8k流式模型

### ISSUE THREAD

**Issue by srdfjy** [Tele-AI/TeleSpeech-ASR#34]
hi，请问现在开源的模型是不是要求输入是16k，且不支持流式推理的？

**Comment by TTTdas** [comment]
> hi，请问现在开源的模型是不是要求输入是16k，且不支持流式推理的？

是的，预训练模型和finetune模型都要求输入是16k。开源的finetune模型是以非流式的方式finetune的

**Comment by srdfjy** [comment]
> > hi，请问现在开源的模型是不是要求输入是16k，且不支持流式推理的？
> 
> 是的，预训练模型和finetune模型都要求输入是16k。开源的finetune模型是以非流式的方式finetune的

好的，THX！
