### ISSUE TITLE
微调版的方言ASR模型计划开源吗？

### ISSUE THREAD

**Issue by lovemefan** [Tele-AI/TeleSpeech-ASR#6]

**Comment by TTTdas** [comment]
更新了一版使用开源数据集KeSpeech微调的模型，方言ASR模型在计划中

**Comment by lq0104** [comment]
> 更新了一版使用开源数据集KeSpeech微调的模型，方言ASR模型在计划中

你好，请问方言ASR模型和使用开源数据集KeSpeech微调的模型的区别是什么

**Comment by rookie0607** [comment]
> 更新了一版使用开源数据集KeSpeech微调的模型，方言ASR模型在计划中

方言模型是用内部数据微调的吗

**Comment by TTTdas** [comment]
> > 更新了一版使用开源数据集KeSpeech微调的模型，方言ASR模型在计划中
> 
> 你好，请问方言ASR模型和使用开源数据集KeSpeech微调的模型的区别是什么

开源数据集KeSpeech微调的模型，是基于pretrain_large，仅利用KeSpeech上1300小时训练数据微调的模型，支持KeSpeech中涉及的8种方言识别

**Comment by brainbpe** [comment]
> > > 更新了一版使用开源数据集KeSpeech微调的模型，方言ASR模型在计划中
> > 
> > 
> > 你好，请问方言ASR模型和使用开源数据集KeSpeech微调的模型的区别是什么
> 
> 开源数据集KeSpeech微调的模型，是基于pretrain_large，仅利用KeSpeech上1300小时训练数据微调的模型，支持KeSpeech中涉及的8种方言识别

后续方言的版本大概什么时候开源？ 你们是用了多大的内部数据finetune的？
